#!/bin/sh
# postrm script for stacksync-server

# Automatically added by dh_installinit
#if [ "$1" = "purge" ] ; then
update-rc.d stacksync-server remove >/dev/null
#fi
# End automatically added section

rm -rf /var/log/stacksync-server
rm /etc/init.d/stacksync-server
