#!/bin/sh
# postrm script for stacksync-server

# Automatically added by dh_installinit
#if [ "$1" = "purge" ] ; then
update-rc.d stacksync-server remove >/dev/null
#fi
# End automatically added section

if [ -d "/var/log/stacksync-server" ]; then
	rm -rf /var/log/stacksync-server
fi

if [ -x "/etc/init.d/stacksync-server" ]; then
	rm /etc/init.d/stacksync-server
fi
