#!/bin/sh
# postinst script for stacksync-server

# Automatically added by dh_installinit
if [ -x "/etc/init.d/stacksync-server" ]; then
	invoke-rc.d stacksync-server stop || exit $?
fi
# End automatically added section
